# Generated by Django 5.0.4 on 2024-05-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
