# Generated by Django 5.0.4 on 2024-05-15 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ecofootprintcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcoFootprintResponse',
            new_name='UserResponse',
        ),
        migrations.RenameField(
            model_name='ecofootprintquestion',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AlterField(
            model_name='ecofootprintquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ecofootprintcategory'),
        ),
    ]
