# Generated by Django 5.0.4 on 2024-05-16 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_ecofootprintresponse_userresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
