# Generated by Django 5.0.4 on 2024-07-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecopiboe_app', '0003_userinfo_profile_picture_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
