# Generated by Django 5.0.4 on 2024-05-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ecofootprintquestion_ecofootprintresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoFootprintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
