# Generated by Django 5.0.4 on 2024-06-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useremailaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailAccount',
        ),
    ]
